




class DataIngestionArtifact:...
class DatavalidationArtifact:...
class ModelTransformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluationArtifact:...
class ModelPusherArtifact:...